kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
    - hostPort: 31001
      containerPort: 31001
    - hostPort: 32000
      containerPort: 32000
    - hostPort: 32500
      containerPort: 32500

